apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params: 
  - name: url
    value: https://github.com/redhat-developer-demos/knative-tutorial
  - name: revision
    value: release/0.7.x
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: knative-tutorial-greeter-image
spec:
  type: image
  params: 
  - name: url
    value: "dev.local/rhdevelopers/knative-tutorial-greeter"
    # if you are on OpenShift uncomment the line below
    #value: "image-registry.openshift-image-registry.svc:5000/tutorial/helloworld"